//
//  LocalizeConstant.swift
//  InfoWebiOS
//
//  Created by Farmood on 30/11/23.
//

import Foundation

// MARK: - Common Label
let mobileError = "mobile_error"
let mobileOk = "mobile_ok"
let mobileYes = "mobile_yes"
let mobileNo = "mobile_no"
let mobileConfirm = "mobile_confirm"
let mobileDone = "mobile_done"
let mobileSubmit = "mobile_submit"
let mobileNoData = "mobile_no_data"
let mobileAdd = "mobile_add"
let mobileEdit = "mobile_edit"
let mobileSave = "mobile_save"
let mobileNoInternetConnection = "mobile_no_internet_connection"
let mobilePleaseCheckYourInternetSettings = "mobile_please_check_your_internet_settings"
let mobileTryAgain = "mobile_try_again"
let mobileLoading = "mobile_loading"
let mobileVersion = "mobile_version"
let mobileInternalServerError = "mobile_internal_server_error"
let mobileTheRequestTimedOut = "mobile_the_request_timed_out"
let mobileSeeMore = "mobile_see_more"
let mobileSeeLess = "mobile_see_less"
let mobileAndPullToRefresh = "mobile_and_pull_to_refresh"
let mobileAndTryAgain = "mobile_and_try_again"

// MARK: - Authentication
let mobileRegister = "mobile_register"
let mobileEmailOrPhoneNumber = "mobile_email_or_phone_number"
let mobilePassword = "mobile_password"
let mobileOldPassword = "mobile_old_password"
let mobileCurrentPassword = "mobile_current_password"
let mobileNewPassword = "mobile_new_password"
let mobileConfirmPassword = "mobile_confirm_password"
let mobileSignUp = "mobile_sign_up"
let mobileOrYouCanRegisterWith = "mobile_or_you_can_register_with"
let mobileAlreadyHaveAnAccount = "mobile_already_have_an_account"
let mobileLoginHere = "mobile_login_here"
let mobileContact = "mobile_contact"
let mobilePleaseEnterEmailOrPhoneNumber = "mobile_please_enter_email_or_phone_number"
let mobilePleaseEnterValidEmail = "mobile_please_enter_valid_email"
let mobilePleaseEnterValidPhoneNumber = "mobile_please_enter_valid_phone_number"
let mobilePleaseEnterNewPassword = "mobile_please_new_enter_password"
let mobilePleaseEnterPassword = "mobile_please_enter_password"
let mobilePleaseEnterConfirmPassword = "mobile_please_enter_confirm_password"
let mobileOldPasswordMustBeAtLeastCharacters = "mobile_old_password_must_be_at_least_characters"
let mobileNewPasswordMustBeAtLeastCharacters = "mobile_new_password_must_be_at_least_characters"
let mobilePasswordMustBeAtLeastCharacters = "mobile_password_must_be_at_least_characters"
let mobileConfirmPasswordDoesNotMatch = "mobile_confirm_password_does_not_match"
let mobilePleaseEnterValidOtpVerification = "mobile_please_enter_valid_otp_verification"
let mobileCancel = "mobile_cancel"
let mobileSelectCountry = "mobile_select_country"
let mobileResend = "mobile_resend"
let mobileSendOtp = "mobile_send_otp"
let mobileForgotPassword = "mobile_forgot_password"
let mobileForgotPasswordQuestionMark = "mobile_forgot_password_with_question_mark"
let mobileOrYouCanLoginWith = "mobile_or_you_can_login_with"
let mobileOr = "mobile_or"
let mobileLoginWithOtp = "mobile_login_with_otp"
let mobileDonTHaveAnAccount = "mobile_don’t_have_an_account"
let mobileLogin = "mobile_login"
let mobileSignUpHere = "mobile_sign_up_here"
let mobileAreYouSureYouWantToLogout = "mobile_are_you_sure,_you_want_to_logout"
let mobileOtp = "mobile_otp"
let mobilePasswordChanged = "mobile_password_changed"
let mobilePasswordChangeSubtitle = "mobile_password_change_subtitle"

// MARK: - MainView
let mobileNews = "mobile_news"
let mobileJournal = "mobile_journal"
let mobileSports = "mobile_sports"
let mobileLottery = "mobile_lottery"
let mobileProfile = "mobile_profile"
let mobileProduct = "mobile_product"
let mobileUpdate = "mobile_update"
let mobileUpdateAvailable = "mobile_update_available"
let mobileNotNow = "mobile_not_now"
let mobileAvailableAppstore = "mobile_is_available_on_appstore"

// MARK: - Side Menu
let mobileFavorite = "mobile_favorite"
let mobileLanguage = "mobile_language"
let mobileLightMode = "mobile_light_mode"
let mobileDarkMode = "mobile_dark_mode"
let mobileChangePassword = "mobile_change_password"
let mobileCustomerSupport = "mobile_customer_support"
let mobileLogout = "mobile_logout"
let mobileAlert = "mobile_alert"
let mobileLoggedOut = "mobile_logged_out"
let mobileLoggedOutSuccessfully = "mobile_logged_out_successfully"

// MARK: - Profile
let mobilePersonalInfo = "mobile_personal_info"
let mobileAnnouncement = "mobile_announcement"
let mobileFeedback = "mobile_feedback"
let mobileNickname = "mobile_nickname"
let mobileEmail = "mobile_email"
let mobileFeedbackContent = "mobile_feedback_content"
let mobileDeletingYourAccountIsPermanent = "mobile_deleting_your_account_is_permanent"
let mobileDeleteAccount = "mobile_delete_account"
let mobileAreYouSureToDeleteAccount = "mobile_are_you_sure_to_delete_account"
let mobilePleaseInputYourFeedback = "mobile_please_input_your_feedback"
let mobileDeleteAccountDescription = "mobile_delete_account_description"
let mobileDoYouWantToUpdateNickname = "mobile_do_you_want_to_update_your_name"
let mobileName = "mobile_name"
let mobilePleaseEnterYourName = "mobile_please_enter_your_name"
let mobileNicknameMustBeAtLeastCharacters = "mobile_nickname_must_be_at_least_characters"
let mobileNameMustBeAtLeastCharacters = "mobile_name_must_be_at_least_characters"

// MARK: - Lottery
let mobileApply = "mobile_apply"
let mobileSelectLotteries = "mobile_selectlotteries"
let mobileFilter = "mobile_filter"
let mobileReset = "mobile_reset"
let mobileworldLotteries = "mobile_world_lotteries"
let mobileLatestLotteryResults = "mobile_latest_lottery_results"
let mobileResult = "mobile_result"
let mobileMoreResult = "mobile_more_result"
let mobileSpecialPrize = "mobile_special_prize"
let mobileLotteryResults = "mobile_lottery_results"
let mobileFirstPrize = "mobile_first_prize"
let mobileSecondPrize = "mobile_second_prize"
let mobileThirdPrize = "mobile_third_prize"
let mobileFourthPrize = "mobile_fourth_prize"
let mobileFifthPrize = "mobile_fifth_prize"
let mobileSixthPrize = "mobile_sixth_prize"
let mobileSeventhPrize = "mobile_seventh_prize"
let mobileEighthPrize = "mobile_eighth_prize"
let mobileDrawId = "mobile_draw_id"
let mobile1stPrize = "mobile_1st_prize"
let mobile2ndPrize = "mobile_2nd_prize"
let mobile3rdPrize = "mobile_3rd_prize"
let mobileSpecial = "mobile_special"
let mobileConsolation = "mobile_consolation"
let mobilePastResults = "mobile_past_results"

// MARK: Journal
let mobileRecentAlbums = "mobile_recent_album"
let mobileIssue = "mobile_issue"
let mobileChooseTheIssue = "mobile_choose_the_issue"
let albumHasEmptyIssue = "mobile_this_album_have_empty_issue"

// MARK: News
let mobileLatestNews = "mobile_latest_news"
let mobilePublished = "mobile_published"
let mobileRecommendedNews = "mobile_recommended_news"

// MARK: Products
let mobileSoftwareProducts = "mobile_software_products"
let mobileReadMore = "mobile_read_more"
let mobileViewDemo = "mobile_view_demo"
let mobileSomethingWentWrong = "mobile_something_went_wrong"
let mobileSupportsNotAvailable = "mobile_supports_not_available"
let mobileProductModules = "mobile_product_modules"
let mobileProductSupport = "mobile_product_support"
let mobilePromotionalActivities = "mobile_promotional_activities"
let mobileOtherExcitingProducts = "mobile_other_exciting_products"
let mobileCanNotOpen = "mobile_can_not_open_"
let mobileAbout = "mobile_about"
let mobileDemoUrl = "mobile_demo_url"
let mobileCopiedToClipboard = "mobile_copied_to_clipboard"
let mobileDemoCredentials = "mobile_demo_credentials"
let mobileUserName = "mobile_user_name"
let mobileContactSupportTitle = "mobile_contact_support_title"
let mobileMessage = "mobile_message"

// MARK: Search
let mobileSearch = "mobile_search"

// MARK: Sport
let mobileFixtures = "mobile_fixtures"
let mobileResults = "mobile_results"
let mobileSummary = "mobile_summary"
let mobileStats = "mobile_stats"
let mobileFt = "mobile_ft"
let mobileHalfTime = "mobile_half_time"
let mobile2ndHalf = "mobile_2nd_half"
let mobile1stHalf = "mobile_1st_half"
let mobile1stQuarter = "mobile_1st_quarter"
let mobile2ndQuarter = "mobile_2nd_quarter"
let mobile3rdQuarter = "mobile_3rd_quarter"
let mobile4thQuarter = "mobile_4th_quarter"
let mobileOverTime = "mobile_over_time"
let mobileLive = "mobile_live"
let mobileUpcoming = "mobile_upcoming"
let mobileCompleted = "mobile_completed"
let mobileLeagues = "mobile_leagues"
